### ISSUE TITLE
Deposit CODECHECK certificates on SciGen.Report

### ISSUE THREAD

**Issue by nuest** [codecheckers/register#32]
I just had a very nice call with @amorim-cjs about how to push new codecheck certificates into the SciGen.Report platform/database. I think it would be great to contibute to SciGen.Report as an inpedendent platform, where users can freely share their post-publication reproduction attempts.

## Notes on the process/integration

* authentication with SciGen.Report API?
  * double layer authentication but so far only for human users: password, and captcha
  * easiest would be a token (manual token fine for now, maybe in the future generate token on user page)
  * add new POST endpoint to access function directly, e.g., `POST /codecheck/submit/access_token/` - to be implemented
  * we submit "on behalf of user" > can we use the ORCID to connect the review with the original author?
    * yes, ORCID integration is planned
  * looking at https://github.com/amorim-cjs/scigen-report/blob/hacktoberfest/source/PeerRep.sql#L88 fields for required data
    * `paper_id` is internal, so we just submit DOI and the platform fetches article metadata from crosreff
    * `user_id` would be a codecheck user
    * `review text` can be certificate summary
    * we have no source for the level of the review, see https://github.com/codecheckers/discussion/issues/12 - we could just use a defensive default, or try to derive this from the summary text (looking for keywords, NLP)
    * the review will soon have a new field for `links` (just a field with a list of links CSV, then add some polish on the UI to separate them and add icons) > we can add the DOI of the report and the code repository as links
* I'd be happy to implement, but not PHP dev; he thinks not much work on PHP end
* real site runs as PHP app on AWS
* how are integration tests done?

## Technical prerequisites

- [ ] ORCID is stored in user profile
- [ ] `links` field for reviews added
- [ ] there is a POST endpoint to add a new review via script
- [ ] token-based authentication works

SciGen.Report is a side project, similar to CODECHECK, so there is no clear timeline for any of these! I might be able to contribute some coding next year.

## Implementation steps

- [ ] register a codecheck user on SciGen.Report so we can post reviews on her behalf
- [ ] get local dev version working
  * `docker-compose up` should be it > almost works!
  * start with `hacktoberfest` branch
- [ ] implement POST endpoint on the server
- [ ] implement R function to submit required information for a review (maybe with a check to see if it is already there? should be possible to realise that by checking for links to the report, or by checking if the paper already as a review by the codecheck user)
- [ ] use function to manually submit reviews for existing codechecks
- [ ] get token for codecheck user
- [ ] integrate encrypted token into the GH action
- [ ] GH action submits to SciGen.Report if a new certificate is added

**Comment by nuest** [comment]
http://scigen.report seems to be down, the repo (link above) is not edited since 4 years ago.

All the more important we get #50 to work!
